apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
  scopes:
    - fleet-stats
    - airport-tracker
    - flight-archiver
    - emergency-alert
    # Note: flight-dashboard does NOT use pubsub - it only uses Service Invocation

